### PR TITLE
support name without issuer like ykman

### PR DESCRIPTION
**Pull request by j0hnsmith**
Given the uri `otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example`

`ykman` returns the code when the query [includes and excludes the issuer](https://github.com/Yubico/yubikey-manager/blob/f493008d78a0ad09016f23dabd1cb658929d9c0e/ykman/cli/oath.py#L543), that is both of these return a code

```
$ ykman oath code -s Example:alice@google.com
$ ykman oath code -s alice@google.com
```

This PR adds the same behaviour to ykoath

### CODE REVIEW

**Comment by yawn** [comment]
Got it, seems sensible. Can you provide a test for this? Should be substantially easier then fiddling with the dumps à la #8.

**Comment by yawn** [comment]
Awesome, thanks @j0hnsmith !

**Comment by yawn** [comment]
Released as 1.0.4.

**Comment by j0hnsmith** [comment]
Great, thanks

**Pull request merged**
