### PR TITLE
Switch pcsclite dependency from cgo to native go

### PR DESCRIPTION
**Pull request by mtibben**
Switch out the pcsclite cgo dependency to a native go dependency.

Please note I don't have a Yubikey, so it would be great to confirm that this works :)

### CODE REVIEW

**Comment by j0hnsmith** [comment]
Doesn't work on my mac because it seems that osx doesn't have a traditional PCSC unix socket any more https://github.com/gballet/go-libpcsclite/commit/2772fd86a8ff4306d2749f610a386bfee9e0d727

**Comment by yawn** [comment]
So this would be Linux only? What's the advantage of this approach in general?

**Comment by j0hnsmith** [comment]
@yawn see the linked pull request. @mtibben is trying to avoid ykoath requiring `CGO=1` but he doesn't have a yubikey to test, he coded what looked like it would work.

I'm going to spend some time to try to get this working.

**Comment by mtibben** [comment]
Looks like it might be complicated on macOS... see https://ludovicrousseau.blogspot.com/search/label/Mac%20OS%20X

CryptoTokenKit is the closed-source Apple library, and looks like PC/SC API is implemented on top?

**Comment by mtibben** [comment]
Also https://ludovicrousseau.blogspot.com/2014/03/level-1-smart-card-support-on-mac-os-x.html

**Comment by yawn** [comment]
Maybe we should offer two versions - Darwin + everything else w/o `CGO`? Would this fit better?

**Comment by yawn** [comment]
Do you thing multiple builds would work here @j0hnsmith ?

**Comment by j0hnsmith** [comment]
Generally speaking, it's nice to be able to have `CGO=0` as much as possible, however I'm not sure it would work for `aws-vault` as I suspect they would want the functionality for all architectures or none at all.

**Comment by yawn** [comment]
So this basically depends on https://github.com/gballet/go-libpcsclite/issues/3 or any other cross OS solution like it.

**Comment by yawn** [comment]
Is this still something you depend on @j0hnsmith / @mtibben? If so, can we try to make some progress here? If the issue here is the missing Yubikey, I can send you one via Amazon ...

**Comment by j0hnsmith** [comment]
I'm pretty sure there is no cross platform solution available at this time. Also, aws-vault doesn't want native yubikey functionality, it prefers external solutions such as [ykman](https://github.com/Yubico/yubikey-manager).

IMO this can be closed.

**Comment by mtibben** [comment]
It's not that a native solution isn't wanted, it's that there is no simple cross-platform way to implement. We can close this

**Pull request closed without merging**
